### ISSUE TITLE
Documentation Topics

### ISSUE THREAD

**Issue by arose** [molstar/molstar#138]
Please, feel free to suggest other topics or pick one to work on. This is for the library docs created in https://github.com/molstar/docs (available at https://molstar.org/docs/).

- [ ] How to contribute to the documentation
- [ ] Interrogate the underlying model data (atoms, residues, distances etc), see #20
- [ ] Approaches for converting a NGL or LiteMol app, see #20
- [ ] Working with custom shapes (creating, zooming), see #134

**Comment by JuroOravec** [comment]
Hi, in my case, I was looking at Molstar as a potential visualisation lib (e.g. similar to the Alpha Orbitals example).

Molstar is great in regards to features and modularity. The Plugin design seems like it could provide an easy way to intercept / listen to user and system events.

However, just understanding what's possible with the Plugins, and their Behaviors and Actions, requires a lot of upfront work. So I suggest adding "Expanding on the [Creating Plugin Instance](https://molstar.org/docs/plugin/) guide" to the list.

Some things that are not clear from that guide as-it-is:
- What even _is_ a plugin?
  - What does it represent?
  - What parts of the Molstar app does it touch / affect? Can I use it to listen and intercept to events? Can I use it to modify some existing functionality?
- Go over each prop on `PluginSpec` and explain what it does.
  - It's not clear how the Actions and Behaviors work, without going into the code. Are they triggered in sequence, or on some triggers?  If triggers, then what are the triggers? Do Actions and Behaviors have to return a value, or is it optional? Can I modify the conditions when they are triggered, or would this have to be handled _inside_ the Action or Behavior?
  - While all default Actions and Behaviors can be seen in DefaultPluginSpec, and their names are transparent, you still need familiarity to know where you would use them. A little description on each of them would help.
- Following should maybe be in a separate page, but there's missing info on what config options, behaviours and actions are supported. They can be found in the source code, but the issue is that if these are not covered in a public documentation / wiki, I can't determine which ones are supported, and which are internal / up-for-change. And in such case, I'm not confident in introducing Molstar to another project.
  - E.g. in case of the above-mentioned guide, it would really help if the `Viewer` options were documented explicitly, instead of linking to the source file. Same for the default Behaviors and Actions.

I'm sorry I can't contribute to the document write up directly, I'm already spread too thin. I hope, though, that the above can be used as a starting points for when the documentation would be expanded.

**Comment by ywu** [comment]
Is there any guidelines for how to write a new parser for file format that is not supported?

**Comment by dsehnal** [comment]
@ywu I've added https://molstar.org/docs/transforms/custom-trajectory.html to the docs. Hopefully, it will help you. If you need more help with the topic, please create a separate issue to discuss it.

**Comment by ywu** [comment]
Thanks so much, David. That's exactly what I'm looking for to get started.

**Comment by klaemo** [comment]
Adding to what @JuroOravec already mentioned, I'd really appreciate documentation describing how to use mol* as a library.

Here's some context: I'm an experienced web developer with little to no knowledge about chemistry. I'm currently working on embedding mol* without its UI into our product. So, for me it would be helpful to have some explainers of the underlying concepts of the mol* API or even an API documentation at all. Currently I'm exploring the TypeScript types (which are great!) in a trial & error kind of way. As the API is rather complex and not very self-describing this is rather tedious.

When I first found https://molstar.org/docs I was confused that it was referring to "plugins" before introducing how to get a simple viewer instance running...until I found out plugins aren't actually plugins but the viewer itself.

Further I'd like to understand 
- `builders` and `managers` and how they relate to each other
-  how to add (figured that out already) and remove `representations`
- animations
- selections

Basically, how do I interact with mol* as a developer?

I don't mean this to sound demanding as I know this is an open source project. Just wanted to give a POV what developers might be interested in.

**Comment by dsehnal** [comment]
Thanks for the feedback @klaemo. The learning curve for this is definitely quite high.

To help us get started on it, do you think you would be able to find some time to add the topics directly to the documentation repository (as pull request(s)) where you fill in some of the things you've figured out and leave other as TODO placeholders?

**Comment by hainm** [comment]
> The learning curve for this is definitely quite high 

yeah, especially for people like me that is not really good at JS code.
- [ ] I have a question about design: What's the relationship among those: model, structure, trajectory, component?-

**Comment by cmdcolin** [comment]
would be curious about docs for using the library from a 'developer' point of view e.g. installing from NPM, getting a basic PDB to display on a create-react-app/vite instance.

**Comment by chdominguez** [comment]
Is the documentation still being developed?

I think Mol* really needs proper documentation and examples. It's a very powerful and versatile molecular visualizer, but for the users, without knowing how it works, it just feels complicated.

**Comment by 0xorial** [comment]
Even a brief couple of paragraphs write could be of great help to people trying to use it!

**Comment by papillot** [comment]
Hi @arose!
At TandemAI, we are looking at using Mol* for our next web application. We have built some toy examples to better learn the concepts and we would like to contribute to the documentation through a gallery of examples, much like what's been done for the NGL gallery powered by CodePen.

We already have a POC on how to import Mol* lib modules into a Pen .
As for the list of examples we thought about, we would like to focus on recipes for key concepts rather than an exhaustive demonstration of features (see infra).

How does that sounds? Any pointer you would like to share about the way this could be integrated into the project if there is indeed an interest?

Here is a list, open to discussion, of the concepts we thought we could exemplify. This would be done at the level of a PluginContext (no React UI), one Pen per example. The goal would be to have even simpler examples than the current ones, which could be analyzed and worked interactively with, when s.o. makes their first steps with the library.

1. Representations
  - Create different representations
    - Create components
    - Create representations with their parameters
  - Update a Representation (type parameters)
  - Change representation visibility (restrict) using selections
  - Remove representations
2. Coloring
  - Color a selection
  - Create a custom coloring provider
  - Update colors of representation
3. Selection
  - Predefined selections
  - Combine selections (for example predefined + distance based)
  - Language (an example using Jmol/Pymol/vmd language)
  - Hydrogens management??
4. View/Camera management
  - Centering
  - Reset view
5. Inspect
  - List entities
  - List interactions from a ligand
6. IO
  - Load from a file

**Comment by rtviii** [comment]
@papillot all of this and more can be found in `https://github.com/molstar/molstar/tree/master/src/examples` if you ignore the React parts. 

> Hi @arose! At TandemAI, we are looking at using Mol* for our next web application. We have built some toy examples to better learn the concepts and we would like to contribute to the documentation through a gallery of examples, much like what's been done for the NGL gallery powered by CodePen.
> 
> We already have a POC on how to import Mol* lib modules into a Pen . As for the list of examples we thought about, we would like to focus on recipes for key concepts rather than an exhaustive demonstration of features (see infra).
> 
> How does that sounds? Any pointer you would like to share about the way this could be integrated into the project if there is indeed an interest?
> 
> Here is a list, open to discussion, of the concepts we thought we could exemplify. This would be done at the level of a PluginContext (no React UI), one Pen per example. The goal would be to have even simpler examples than the current ones, which could be analyzed and worked interactively with, when s.o. makes their first steps with the library.
> 
>     1. Representations
> 
> 
>     * Create different representations
>       
>       * Create components
>       * Create representations with their parameters
> 
>     * Update a Representation (type parameters)
> 
>     * Change representation visibility (restrict) using selections
> 
>     * Remove representations
> 
> 
>     2. Coloring
> 
> 
>     * Color a selection
> 
>     * Create a custom coloring provider
> 
>     * Update colors of representation
> 
> 
>     3. Selection
> 
> 
>     * Predefined selections
> 
>     * Combine selections (for example predefined + distance based)
> 
>     * Language (an example using Jmol/Pymol/vmd language)
> 
>     * Hydrogens management??
> 
> 
>     4. View/Camera management
> 
> 
>     * Centering
> 
>     * Reset view
> 
> 
>     5. Inspect
> 
> 
>     * List entities
> 
>     * List interactions from a ligand
> 
> 
>     6. IO
> 
> 
>     * Load from a file

**Comment by papillot** [comment]
@rtviii I know about the examples. The key part is this "_The goal would be to have even simpler examples than the current ones, which could be analyzed and worked interactively with, when s.o. makes their first steps with the library._" which means finding the sweet spot for a dev that is just starting with this library and who might be overwhelmed with the current examples.

**Comment by QDMarkMan** [comment]
Here is the documentation generated by AI (Devin): https://deepwiki.com/molstar/molstar. It may be quite helpful for developers and contributors.

**Comment by noam-ackerman** [comment]
Hey @arose and everyone in this discussion :) 
I am trying to use Molstar as a 3d viewer that corresponds to user selections in our product form.
the 3d viewer should start as a clean slate with the protein chains in color gray.  residues and molecules are being highlighted as the user select them in the form in various inputs just to indicate the user it's own selections. 
for example i uploaded a PDB with structure containing identical chain A and B.  they choose chain A - ideally i would like to have chain B gray and chain A a specific color indicating selection and also to represent that B exist but is not currently selected. both cartoon.
then the user select specific residue number / a molecule , i want it to be highlighted in ball+stick representation (in the selected chain/s which is A in our example use case) 
i struggle figuring out how the representation API work in terms of selecting specific entities /components. when trying to create model and structure and add to it representation it's just highlighting the whole structure. I'm guessing cause I'm sending "structure" as the component but i don't find how i can select a specific chain / residue. 
was wondering if an API for that kind of use even exist, it's a bit hard to know because i can't find anything to how to add representations and choose specific entities via the official docs. 

would be happy also to know at least if it's not possible, just to not be stuck in uncertainty whether Molstar is the right choice for us or not.  

thank you!

**Comment by duerrsimon** [comment]
@papillot  I would love such a list of examples you proposed. @rtviii the current "examples" are just implementations of the library and are really not that useful. 

I have the following suggests for improvements for the docs. The viewer is amazing but the documentation is really bad in my opinion. I know you put a lot of effort and time into this library so it would be great if the documentation could be improved. 

Here are some constructive suggestions what you could do:

- Provide more examples for common use cases such as selections and changing overpaint or representation for a selection. This page https://molstar.org/docs/plugin/selections/ explains just how to do some selections but then has no guidance how to use the selections. The selection page should also explain the concept of a loci. This question continues to pop up regularly. 

- Explain more clearly the concepts in the library like Selection language, hierarchy manager, components

- As a developer for simple questions don't give examples in the source code (e.g you find many examples for the selection language in the source code). Yes, technically correct but there is a lot of boilerplate there. I also came across some instances where the developers link source code examples in some stale branch.

- Make the documentation more consistent: e.g in the selections in the developer docs page sometimes you use : window.molstar? sometimes mstar.managers Sometimes you import like this: import { Structure } from '../mol-model/structure';, sometimes like this: import { Structure, StructureProperties, } from "molstar/lib/mol-model/structure".
